In [1]:
# check which version of the python colab is using currently
import sys
print(sys.version)

3.13.15 (main, Aug  6 2026, 11:06:23) [GCC 11.4.0]


In [2]:
! pip install numpy

In [3]:
! pip install sentence_transformers

In [4]:
# here q means quiet
! pip install -q sentence_transformers

In [5]:
import numpy as np
from sentence_transformers import SentenceTransformer
print("Environment is ready!!")

Environment is ready!!


In [6]:
# Load the embedding model
model = SentenceTransformer("all-MiniLM-L6-v2")

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.5k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 90.9MB            

model.safetensors: downloading bytes:           |  0.00B            

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [7]:
# encode the text
text = "I love programming"
embedding = model.encode(text)
print(embedding)

[-3.61786447e-02 -1.27736982e-02  3.00627900e-03 -1.69034638e-02
  9.48426407e-03 -6.51517212e-02  9.37663689e-02  7.14234859e-02
  1.85262877e-02  5.35826795e-02 -8.24748278e-02  1.80089418e-02
  3.44095901e-02  1.51711525e-02  3.18937637e-02 -1.89523567e-02
 -8.73143449e-02 -3.99797037e-02 -5.35774417e-03 -7.61753246e-02
 -1.42133251e-01 -6.11384073e-03 -4.14068364e-02 -3.20393853e-02
  5.18484078e-02  9.73950699e-02 -1.16527581e-03 -4.83810529e-02
  1.42009510e-02 -7.73504227e-02 -9.08909291e-02  9.55949202e-02
  8.43655840e-02  6.60044476e-02  1.65076517e-02  5.63961789e-02
  8.12913999e-02 -6.16290644e-02  8.56057461e-03  5.73750352e-03
 -1.09042339e-01  5.53962328e-02  3.23738344e-02 -3.92971635e-02
 -4.51563997e-03 -3.88994105e-02 -3.04347835e-02 -5.73263951e-02
  8.27749297e-02  3.39200497e-02  1.93318573e-03 -1.74611136e-02
 -2.32558697e-04 -4.40390930e-02 -2.35111406e-03  4.77190508e-04
  6.99083656e-02  1.26314834e-02 -8.38911533e-03 -5.11303656e-02
 -4.02324796e-02  3.02443

In [8]:
print(type(embedding))

<class 'numpy.ndarray'>


In [9]:
print(embedding.shape)

(384,)


In [10]:
# let's check the first 10 numbers of the embedding list
print(embedding[:10])

[-0.03617864 -0.0127737   0.00300628 -0.01690346  0.00948426 -0.06515172
  0.09376637  0.07142349  0.01852629  0.05358268]


In [11]:
# Now let's see the same thing for more than one sentence

sentences = [
  "I love programming",
  "I enjoy writing code",
  "I like eating pizza"
]

embedding_sentences = model.encode(sentences)
print(embedding_sentences.shape)

(3, 384)


* Sentence 1 → 384 numbers
* Sentence 2 → 384 numbers
* Sentence 3 → 384 numbers

#### to check the semantically similar sentences, the most common used method is **COSINE SIMILARITY**

In [12]:
from sklearn.metrics.pairwise import cosine_similarity

In [13]:
scores = cosine_similarity(
    [embedding_sentences[0]],
    embedding_sentences[1:]
)
print(scores)

[[0.71464443 0.41065878]]


In [14]:
print(embedding_sentences[0].shape)
print(embedding_sentences[1:].shape)
print([embedding_sentences[0]])

(384,)
(2, 384)
[array([-3.61786447e-02, -1.27736982e-02,  3.00627900e-03, -1.69034638e-02,
        9.48426407e-03, -6.51517212e-02,  9.37663689e-02,  7.14234859e-02,
        1.85262877e-02,  5.35826795e-02, -8.24748278e-02,  1.80089418e-02,
        3.44095901e-02,  1.51711525e-02,  3.18937637e-02, -1.89523567e-02,
       -8.73143449e-02, -3.99797037e-02, -5.35774417e-03, -7.61753246e-02,
       -1.42133251e-01, -6.11384073e-03, -4.14068364e-02, -3.20393853e-02,
        5.18484078e-02,  9.73950699e-02, -1.16527581e-03, -4.83810529e-02,
        1.42009510e-02, -7.73504227e-02, -9.08909291e-02,  9.55949202e-02,
        8.43655840e-02,  6.60044476e-02,  1.65076517e-02,  5.63961789e-02,
        8.12913999e-02, -6.16290644e-02,  8.56057461e-03,  5.73750352e-03,
       -1.09042339e-01,  5.53962328e-02,  3.23738344e-02, -3.92971635e-02,
       -4.51563997e-03, -3.88994105e-02, -3.04347835e-02, -5.73263951e-02,
        8.27749297e-02,  3.39200497e-02,  1.93318573e-03, -1.74611136e-02,
       -

In [15]:
# Let's check for another experimental sentences

sentences_2 = [
    "I love programming",
    "Python is my favorite programming language",
    "The weather is beautiful today",
    "I enjoy writing software",
    "Pizza is my favorite food"
]

embedding_sentences2 = model.encode(sentences_2)

print(embedding_sentences2.shape)

(5, 384)


In [16]:
scores_2 = cosine_similarity(
    [embedding_sentences2[0]],
     embedding_sentences2[1:]
)

print(scores_2)

[[0.6842448  0.06664523 0.70664155 0.36365208]]


# **A small project: semantic search engine**

a working system that finds one most relevant document.

In [17]:
# create our own document list

documents = [
    "Python is a popular programming language used for web development, automation, and data science.",
    "Machine learning allows computers to learn patterns from data.",
    "Docker is a tool used to package applications and their dependencies into containers.",
    "Python functions are reusable blocks of code that perform a specific task.",
    "SQL is a language used to communicate with and query relational databases.",
    "Git is a version control system used to track changes in source code."
]

print(len(documents))

6


In [18]:
# convert the doc texts into numbers
docs_embeddings = model.encode(documents)

print(docs_embeddings.shape) # 6 sentences with 384 dimensions each

(6, 384)


In [19]:
# user's query
query = "How can I learn Python programming?"

# query embedding
q_embed = model.encode(query)
print(q_embed.shape)

(384,)


In [20]:
sim_scores = cosine_similarity(
    [q_embed],
    docs_embeddings
)

print(sim_scores)

[[0.68622136 0.19541419 0.05452027 0.39474785 0.16473888 0.0800138 ]]


In [21]:
# check the highest similarity score

best_index = np.argmax(sim_scores)
print(best_index)

0


In [22]:
# retrieve the document of the at the best index

print(documents[best_index])

Python is a popular programming language used for web development, automation, and data science.


# **Build Top-K semantic Search**
return the top 3 most relevant documents

In [31]:
documents = [
  "Python is a popular programming language used for web development, automation, and data science.",
  "Machine learning allows computers to learn patterns from data.",
  "Docker is a tool used to package applications and their dependencies into containers.",
  "Python functions are reusable blocks of code that perform a specific task.",
  "SQL is a language used to communicate with and query relational databases.",
  "Git is a version control system used to track changes in source code."
]

print(len(documents))

6


In [32]:
# convert the document text into vectors

document_embed = model.encode(documents)

print(document_embed.shape)

(6, 384)


In [33]:
# user's query

query = "How does the docker work?"

q_embedding = model.encode(query)
print(q_embedding.shape)

(384,)


In [34]:
similarity_scores = cosine_similarity(
    [q_embedding],
    document_embed
)

print(similarity_scores)

[[0.09098983 0.07222727 0.73203504 0.10482584 0.0562552  0.24179225]]


sort the scores in descending order for finding top-3

In [35]:
ascending_index = np.argsort(similarity_scores[0])
print(ascending_index)

reversed_index = ascending_index[::-1]
print(reversed_index)

[4 1 0 3 5 2]
[2 5 3 0 1 4]


In [36]:
top_3_indices = reversed_index[:3]
print(top_3_indices)

[2 5 3]


In [37]:
print(documents[0])
print(documents[3])
print(documents[1])

Python is a popular programming language used for web development, automation, and data science.
Python functions are reusable blocks of code that perform a specific task.
Machine learning allows computers to learn patterns from data.


In [38]:
for i in top_3_indices:
  print(documents[i])

Docker is a tool used to package applications and their dependencies into containers.
Git is a version control system used to track changes in source code.
Python functions are reusable blocks of code that perform a specific task.


##**Final project: Mini semantic search engine**

Goal:

Build a program where a user can type any query, and your system returns the top 3 most relevant documents with their similarity scores.

In [39]:
# list of our documents
documents = [
    "Python is a popular programming language used for web development, automation, data analysis, and artificial intelligence. Its simple syntax makes it beginner-friendly.",

    "Machine learning is a branch of artificial intelligence where computers learn patterns from data. Common applications include prediction, classification, recommendation systems, and image recognition.",

    "Retrieval-Augmented Generation, or RAG, combines information retrieval with large language models. Relevant documents are retrieved first and then provided to the language model as context for generating an answer.",

    "SQL is a language used to store, retrieve, and manipulate data in relational databases. It can be used to filter records, join tables, insert data, and update existing information.",

    "Docker is a platform for packaging applications and their dependencies into lightweight containers. Containers help developers run software consistently across different environments.",

    "Git is a distributed version control system used to track changes in source code. Developers use Git to create branches, collaborate with teammates, review changes, and maintain project history.",

    "Cloud computing provides computing resources such as servers, storage, databases, and networking over the internet. Popular cloud platforms include services for application hosting, data storage, and scalable infrastructure.",

    "An API allows different software applications to communicate with each other. REST APIs commonly use HTTP methods such as GET, POST, PUT, and DELETE to exchange data.",

    "React is a JavaScript library for building user interfaces. It allows developers to create reusable components and efficiently update the user interface when application data changes.",

    "Cybersecurity focuses on protecting computers, networks, applications, and data from unauthorized access and attacks. Important areas include authentication, authorization, encryption, and vulnerability management."
]

In [40]:
# create the embeddings of our documents
embedding_docs = model.encode(documents)

# shape of the docs embeddings
print(embedding_docs.shape)

(10, 384)


### Queries to test:
1. How can I learn a programming language easily?
2. What technology can I use to package my application?
3. How can software systems communicate with each other?
4. What can I use to protect my application?
5. How does RAG provide information to an AI model?
6. Where can I store and query structured data?

In [103]:
user_query = "How can I learn a programming language easily?"

user_query_embed = model.encode(user_query)
print(user_query_embed.shape)

(384,)


In [104]:
# calculate the similarity scores between the user query and the documents given
sim_scores = cosine_similarity(
    [user_query_embed],
    embedding_docs
)

print(sim_scores)

[[ 0.49091697  0.1925033   0.15702268  0.18604109 -0.01266885  0.03434162
   0.01177624  0.11192895  0.17699805  0.0419074 ]]


In [105]:
asc_index_sim_scores = np.argsort(sim_scores[0])
print(asc_index_sim_scores)

[4 6 5 9 7 2 8 3 1 0]


In [106]:
reverse_index_sim_scores = asc_index_sim_scores[::-1]
print(reverse_index_sim_scores)

[0 1 3 8 2 7 9 5 6 4]


In [107]:
top_3 = reverse_index_sim_scores[:3]
print(top_3)

[0 1 3]


In [108]:
for i in top_3:
  print(documents[i])

Python is a popular programming language used for web development, automation, data analysis, and artificial intelligence. Its simple syntax makes it beginner-friendly.
Machine learning is a branch of artificial intelligence where computers learn patterns from data. Common applications include prediction, classification, recommendation systems, and image recognition.
SQL is a language used to store, retrieve, and manipulate data in relational databases. It can be used to filter records, join tables, insert data, and update existing information.


Let's say threshold is 0.3

In [109]:
best_score_index = top_3[0]
print(best_score_index)

0


In [110]:
best_score = sim_scores[0][best_score_index]
print(best_score)

0.49091697


In [112]:
if best_score < 0.3:
  print("No relevant document is found!")
else:
  for i in top_3:
    print(documents[i])

Python is a popular programming language used for web development, automation, data analysis, and artificial intelligence. Its simple syntax makes it beginner-friendly.
Machine learning is a branch of artificial intelligence where computers learn patterns from data. Common applications include prediction, classification, recommendation systems, and image recognition.
SQL is a language used to store, retrieve, and manipulate data in relational databases. It can be used to filter records, join tables, insert data, and update existing information.
